# Generated by Django 3.2.8 on 2021-12-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='code',
            new_name='title',
        ),
    ]
