# Generated by Django 3.2.8 on 2021-12-15 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations_app', '0002_rename_code_site_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('title', models.CharField(max_length=64)),
                ('creation_time', models.DateTimeField()),
            ],
        ),
    ]
