# Generated by Django 3.2.8 on 2021-12-15 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations_app', '0004_alter_hazard_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
